import type { Question } from "@mathprep/core";

const SOURCE = "MathPrep original (AMC 8 style)";

/**
 * Original questions written in the style of the AMC 8. Text may contain
 * inline LaTeX delimited by $...$. Choices follow the AMC convention of
 * ascending order, so the correct letter varies naturally.
 *
 * Difficulty tiers mirror the real exam: easy ≈ #1–10, medium ≈ #11–20,
 * hard ≈ #21–25.
 */
export const QUESTION_BANK: Question[] = [
  // ── Arithmetic & Ratios ────────────────────────────────────────────────
  {
    id: "arith-01",
    topic: "arithmetic",
    difficulty: "easy",
    stem: String.raw`What is the value of $\frac{1}{2} + \frac{1}{3} + \frac{1}{6}$?`,
    choices: [
      String.raw`$\frac{2}{3}$`,
      String.raw`$\frac{5}{6}$`,
      String.raw`$\frac{11}{12}$`,
      "$1$",
      String.raw`$\frac{7}{6}$`,
    ],
    answerIndex: 3,
    explanation: String.raw`Using a common denominator of 6: $\frac{3}{6} + \frac{2}{6} + \frac{1}{6} = \frac{6}{6} = 1$.`,
    source: SOURCE,
  },
  {
    id: "arith-02",
    topic: "arithmetic",
    difficulty: "easy",
    stem: "A jacket priced at $\\$40$ is on sale for $25\\%$ off. What is the sale price in dollars?",
    choices: ["$10$", "$25$", "$28$", "$30$", "$32$"],
    answerIndex: 3,
    explanation: String.raw`A $25\%$ discount means paying $75\%$ of the price: $0.75 \times 40 = 30$ dollars.`,
    source: SOURCE,
  },
  {
    id: "arith-03",
    topic: "arithmetic",
    difficulty: "medium",
    stem: String.raw`A hose fills $\frac{3}{4}$ of a water tank in 18 minutes. At the same rate, how many minutes does it take to fill the whole tank?`,
    choices: ["$20$", "$22$", "$24$", "$27$", "$30$"],
    answerIndex: 2,
    explanation: String.raw`Filling $\frac{3}{4}$ takes 18 minutes, so each $\frac{1}{4}$ takes 6 minutes and the full tank takes $4 \times 6 = 24$ minutes.`,
    source: SOURCE,
  },
  {
    id: "arith-04",
    topic: "arithmetic",
    difficulty: "medium",
    stem: "Maya walks 2 miles at 4 miles per hour, then runs 2 miles at 6 miles per hour. What is her average speed, in miles per hour, for the whole trip?",
    choices: ["$4.6$", "$4.8$", "$5.0$", "$5.2$", "$5.4$"],
    answerIndex: 1,
    explanation: String.raw`Walking takes $\frac{2}{4} = \frac{1}{2}$ hour and running takes $\frac{2}{6} = \frac{1}{3}$ hour, so 4 miles take $\frac{5}{6}$ hour. Average speed is $4 \div \frac{5}{6} = \frac{24}{5} = 4.8$ mph. Average speed is total distance over total time — not the average of 4 and 6.`,
    source: SOURCE,
  },
  {
    id: "arith-05",
    topic: "arithmetic",
    difficulty: "medium",
    stem: String.raw`A store applies a $20\%$ discount, then takes an additional $25\%$ off the discounted price. The combined effect equals a single discount of what percent?`,
    choices: ["$35$", "$40$", "$42.5$", "$45$", "$50$"],
    answerIndex: 1,
    explanation: String.raw`Paying $80\%$ and then $75\%$ of that leaves $0.80 \times 0.75 = 0.60$ of the original price, which is a $40\%$ discount. Successive discounts don't simply add.`,
    source: SOURCE,
  },
  {
    id: "arith-06",
    topic: "arithmetic",
    difficulty: "hard",
    stem: String.raw`What is the value of the product $\left(1-\frac{1}{2}\right)\left(1-\frac{1}{3}\right)\left(1-\frac{1}{4}\right)\cdots\left(1-\frac{1}{2026}\right)$?`,
    choices: [
      String.raw`$\frac{1}{2026}$`,
      String.raw`$\frac{1}{2025}$`,
      String.raw`$\frac{1}{1013}$`,
      String.raw`$\frac{2}{2025}$`,
      String.raw`$\frac{2025}{2026}$`,
    ],
    answerIndex: 0,
    explanation: String.raw`Each factor simplifies: the product is $\frac{1}{2} \cdot \frac{2}{3} \cdot \frac{3}{4} \cdots \frac{2025}{2026}$. Every numerator cancels the previous denominator (telescoping), leaving $\frac{1}{2026}$.`,
    source: SOURCE,
  },

  // ── Number Theory ──────────────────────────────────────────────────────
  {
    id: "nt-01",
    topic: "number-theory",
    difficulty: "easy",
    stem: "What is the greatest common divisor of 36 and 84?",
    choices: ["$4$", "$6$", "$9$", "$12$", "$18$"],
    answerIndex: 3,
    explanation: String.raw`$36 = 2^2 \cdot 3^2$ and $84 = 2^2 \cdot 3 \cdot 7$. The common part is $2^2 \cdot 3 = 12$.`,
    source: SOURCE,
  },
  {
    id: "nt-02",
    topic: "number-theory",
    difficulty: "easy",
    stem: "What is the sum of all prime numbers between 20 and 30?",
    choices: ["$42$", "$48$", "$52$", "$58$", "$60$"],
    answerIndex: 2,
    explanation:
      "The only primes between 20 and 30 are 23 and 29 (21, 25, 27 are composite and even numbers can't be prime). Their sum is 52.",
    source: SOURCE,
  },
  {
    id: "nt-03",
    topic: "number-theory",
    difficulty: "medium",
    stem: "A number leaves remainder 3 when divided by 5, and remainder 2 when divided by 4. What is the smallest positive number with this property?",
    choices: ["$8$", "$13$", "$18$", "$23$", "$38$"],
    answerIndex: 2,
    explanation:
      "Numbers with remainder 3 when divided by 5: 3, 8, 13, 18, … Checking each against division by 4: 3 leaves 3, 8 leaves 0, 13 leaves 1, and 18 leaves 2. So 18 is the smallest.",
    source: SOURCE,
  },
  {
    id: "nt-04",
    topic: "number-theory",
    difficulty: "medium",
    stem: "How many positive divisors does 72 have?",
    choices: ["$8$", "$9$", "$10$", "$12$", "$16$"],
    answerIndex: 3,
    explanation: String.raw`$72 = 2^3 \cdot 3^2$. The divisor count is $(3+1)(2+1) = 12$: each divisor picks a power of 2 (four ways) and a power of 3 (three ways).`,
    source: SOURCE,
  },
  {
    id: "nt-05",
    topic: "number-theory",
    difficulty: "medium",
    stem: String.raw`What is the units digit of $7^{2026}$?`,
    choices: ["$1$", "$3$", "$5$", "$7$", "$9$"],
    answerIndex: 4,
    explanation: String.raw`Units digits of powers of 7 cycle with period 4: $7, 9, 3, 1, 7, 9, \ldots$ Since $2026 = 4 \cdot 506 + 2$, the units digit matches $7^2 = 49$, which is 9.`,
    source: SOURCE,
  },
  {
    id: "nt-06",
    topic: "number-theory",
    difficulty: "hard",
    stem: String.raw`What is the smallest positive integer $n$ such that $n! = 1 \cdot 2 \cdot 3 \cdots n$ is divisible by 1000?`,
    choices: ["$10$", "$12$", "$15$", "$20$", "$25$"],
    answerIndex: 2,
    explanation: String.raw`$1000 = 2^3 \cdot 5^3$, so $n!$ needs three factors of 5. The multiples of 5 up to $n$ supply them: $10!$ and $12!$ contain only two (from 5 and 10), while $15!$ contains three (from 5, 10, and 15). Factors of 2 are plentiful, so $n = 15$.`,
    source: SOURCE,
  },

  // ── Algebra & Patterns ─────────────────────────────────────────────────
  {
    id: "alg-01",
    topic: "algebra",
    difficulty: "easy",
    stem: "If $3x + 5 = 20$, what is the value of $x$?",
    choices: ["$4$", "$5$", "$6$", "$7$", "$8$"],
    answerIndex: 1,
    explanation: String.raw`Subtract 5 from both sides: $3x = 15$, so $x = 5$.`,
    source: SOURCE,
  },
  {
    id: "alg-02",
    topic: "algebra",
    difficulty: "easy",
    stem: String.raw`The sequence $4, 7, 10, 13, \ldots$ increases by 3 each step. What is its 10th term?`,
    choices: ["$27$", "$29$", "$31$", "$33$", "$35$"],
    answerIndex: 2,
    explanation: String.raw`The 10th term is the first term plus nine steps: $4 + 9 \times 3 = 31$.`,
    source: SOURCE,
  },
  {
    id: "alg-03",
    topic: "algebra",
    difficulty: "medium",
    stem: "Maya is 3 years more than twice her brother Leo's age. Their ages add up to 24. How old is Leo?",
    choices: ["$5$", "$6$", "$7$", "$8$", "$9$"],
    answerIndex: 2,
    explanation: String.raw`Let Leo's age be $v$. Then Maya is $2v + 3$, and $v + (2v + 3) = 24$ gives $3v = 21$, so $v = 7$.`,
    source: SOURCE,
  },
  {
    id: "alg-04",
    topic: "algebra",
    difficulty: "medium",
    stem: "If $x + y = 10$ and $x - y = 4$, what is the value of $x \\cdot y$?",
    choices: ["$18$", "$20$", "$21$", "$24$", "$28$"],
    answerIndex: 2,
    explanation: String.raw`Adding the equations gives $2x = 14$, so $x = 7$ and $y = 3$. Then $x \cdot y = 21$.`,
    source: SOURCE,
  },
  {
    id: "alg-05",
    topic: "algebra",
    difficulty: "medium",
    stem: "A farm has chickens and rabbits — 20 animals in all, with 56 legs altogether. How many rabbits are there?",
    choices: ["$6$", "$7$", "$8$", "$9$", "$10$"],
    answerIndex: 2,
    explanation: String.raw`With $r$ rabbits and $20 - r$ chickens: $4r + 2(20 - r) = 56$, so $2r = 16$ and $r = 8$.`,
    source: SOURCE,
  },
  {
    id: "alg-06",
    topic: "algebra",
    difficulty: "hard",
    stem: String.raw`The sum $1 + 2 + 3 + \cdots + n$ equals 231. What is $n$?`,
    choices: ["$20$", "$21$", "$22$", "$23$", "$24$"],
    answerIndex: 1,
    explanation: String.raw`The sum is $\frac{n(n+1)}{2} = 231$, so $n(n+1) = 462 = 21 \times 22$. Thus $n = 21$.`,
    source: SOURCE,
  },

  // ── Geometry ───────────────────────────────────────────────────────────
  {
    id: "geo-01",
    topic: "geometry",
    difficulty: "easy",
    stem: "A rectangle has perimeter 26 and one side of length 8. What is its area?",
    choices: ["$32$", "$36$", "$40$", "$44$", "$48$"],
    answerIndex: 2,
    explanation: String.raw`The two side lengths sum to $26 \div 2 = 13$, so the other side is $13 - 8 = 5$. The area is $8 \times 5 = 40$.`,
    source: SOURCE,
  },
  {
    id: "geo-02",
    topic: "geometry",
    difficulty: "easy",
    stem: String.raw`Two angles of a triangle measure $55^\circ$ and $65^\circ$. What is the measure of the third angle, in degrees?`,
    choices: ["$45$", "$50$", "$55$", "$60$", "$70$"],
    answerIndex: 3,
    explanation: String.raw`The angles of a triangle sum to $180^\circ$: $180 - 55 - 65 = 60$.`,
    source: SOURCE,
  },
  {
    id: "geo-03",
    topic: "geometry",
    difficulty: "medium",
    stem: "A right triangle has legs of length 9 and 12. What is the length of its hypotenuse?",
    choices: ["$12$", "$13$", "$15$", "$17$", "$21$"],
    answerIndex: 2,
    explanation: String.raw`By the Pythagorean theorem, $9^2 + 12^2 = 81 + 144 = 225 = 15^2$. (This is a 3–4–5 triangle scaled by 3.)`,
    source: SOURCE,
  },
  {
    id: "geo-04",
    topic: "geometry",
    difficulty: "medium",
    stem: "A square with side length 6 has the same perimeter as an equilateral triangle. What is the side length of the triangle?",
    choices: ["$6$", "$7$", "$8$", "$9$", "$12$"],
    answerIndex: 2,
    explanation: String.raw`The square's perimeter is $4 \times 6 = 24$, so each of the triangle's three equal sides is $24 \div 3 = 8$.`,
    source: SOURCE,
  },
  {
    id: "geo-05",
    topic: "geometry",
    difficulty: "medium",
    stem: String.raw`A cube has surface area $54$ square centimeters. What is its volume, in cubic centimeters?`,
    choices: ["$18$", "$21$", "$27$", "$36$", "$81$"],
    answerIndex: 2,
    explanation: String.raw`A cube has 6 faces, so each face has area $54 \div 6 = 9$ and the edge is 3. The volume is $3^3 = 27$.`,
    source: SOURCE,
  },
  {
    id: "geo-06",
    topic: "geometry",
    difficulty: "hard",
    stem: "A circle is inscribed in a square with side length 4, touching all four sides. What is the area of the region inside the square but outside the circle?",
    choices: [
      String.raw`$16 - 4\pi$`,
      String.raw`$4\pi - 8$`,
      String.raw`$8 - \pi$`,
      String.raw`$16 - 2\pi$`,
      String.raw`$16 - \pi$`,
    ],
    answerIndex: 0,
    explanation: String.raw`The square has area $16$. The inscribed circle has radius 2 (half the side), so its area is $\pi \cdot 2^2 = 4\pi$. The leftover region is $16 - 4\pi$.`,
    source: SOURCE,
  },

  // ── Counting ───────────────────────────────────────────────────────────
  {
    id: "count-01",
    topic: "counting",
    difficulty: "easy",
    stem: "How many different ways can the four letters of MATH be arranged in a row?",
    choices: ["$6$", "$12$", "$18$", "$24$", "$36$"],
    answerIndex: 3,
    explanation: String.raw`There are 4 choices for the first letter, then 3, then 2, then 1: $4 \times 3 \times 2 \times 1 = 24$.`,
    source: SOURCE,
  },
  {
    id: "count-02",
    topic: "counting",
    difficulty: "easy",
    stem: "An ice cream shop offers 3 flavors, 2 cone types, and 2 toppings. How many different combinations of one flavor, one cone, and one topping are possible?",
    choices: ["$7$", "$10$", "$12$", "$18$", "$24$"],
    answerIndex: 2,
    explanation: String.raw`By the counting principle, multiply the independent choices: $3 \times 2 \times 2 = 12$.`,
    source: SOURCE,
  },
  {
    id: "count-03",
    topic: "counting",
    difficulty: "medium",
    stem: "How many three-digit numbers have all three digits odd?",
    choices: ["$25$", "$75$", "$100$", "$125$", "$225$"],
    answerIndex: 3,
    explanation: String.raw`Each digit can be 1, 3, 5, 7, or 9 — five choices per position: $5 \times 5 \times 5 = 125$.`,
    source: SOURCE,
  },
  {
    id: "count-04",
    topic: "counting",
    difficulty: "medium",
    stem: "Six friends meet, and each pair shakes hands exactly once. How many handshakes take place?",
    choices: ["$12$", "$15$", "$18$", "$30$", "$36$"],
    answerIndex: 1,
    explanation: String.raw`Each of 6 people shakes 5 hands, but $6 \times 5 = 30$ counts every handshake twice, giving $30 \div 2 = 15$.`,
    source: SOURCE,
  },
  {
    id: "count-05",
    topic: "counting",
    difficulty: "medium",
    stem: "How many paths are there from $(0, 0)$ to $(3, 3)$ if each step moves one unit right or one unit up?",
    choices: ["$6$", "$9$", "$18$", "$20$", "$27$"],
    answerIndex: 3,
    explanation: String.raw`Every path uses exactly 3 rights and 3 ups in some order. Choosing which 3 of the 6 steps are rights gives $\binom{6}{3} = 20$.`,
    source: SOURCE,
  },
  {
    id: "count-06",
    topic: "counting",
    difficulty: "hard",
    stem: "How many three-digit numbers have digits that add up to exactly 5?",
    choices: ["$10$", "$12$", "$15$", "$20$", "$21$"],
    answerIndex: 2,
    explanation: String.raw`Count by first digit (which must be at least 1). If it is 1, the last two digits sum to 4 (5 ways); if 2, they sum to 3 (4 ways); then 3 ways, 2 ways, and 1 way for first digits 3, 4, 5. Total: $5+4+3+2+1 = 15$.`,
    source: SOURCE,
  },

  // ── Probability ────────────────────────────────────────────────────────
  {
    id: "prob-01",
    topic: "probability",
    difficulty: "easy",
    stem: "A fair six-sided die is rolled once. What is the probability of rolling a number greater than 4?",
    choices: [
      String.raw`$\frac{1}{6}$`,
      String.raw`$\frac{1}{4}$`,
      String.raw`$\frac{1}{3}$`,
      String.raw`$\frac{1}{2}$`,
      String.raw`$\frac{2}{3}$`,
    ],
    answerIndex: 2,
    explanation: String.raw`Two of the six equally likely outcomes (5 and 6) are greater than 4: $\frac{2}{6} = \frac{1}{3}$.`,
    source: SOURCE,
  },
  {
    id: "prob-02",
    topic: "probability",
    difficulty: "easy",
    stem: "A bag holds 3 red marbles and 5 blue marbles. One marble is drawn at random. What is the probability it is red?",
    choices: [
      String.raw`$\frac{1}{3}$`,
      String.raw`$\frac{3}{8}$`,
      String.raw`$\frac{1}{2}$`,
      String.raw`$\frac{3}{5}$`,
      String.raw`$\frac{5}{8}$`,
    ],
    answerIndex: 1,
    explanation: String.raw`There are $3 + 5 = 8$ marbles in total, and 3 are red, so the probability is $\frac{3}{8}$.`,
    source: SOURCE,
  },
  {
    id: "prob-03",
    topic: "probability",
    difficulty: "medium",
    stem: "Three fair coins are flipped. What is the probability of getting exactly two heads?",
    choices: [
      String.raw`$\frac{1}{8}$`,
      String.raw`$\frac{1}{4}$`,
      String.raw`$\frac{3}{8}$`,
      String.raw`$\frac{1}{2}$`,
      String.raw`$\frac{5}{8}$`,
    ],
    answerIndex: 2,
    explanation: String.raw`Of the $2^3 = 8$ equally likely outcomes, exactly two heads occurs in 3 of them (HHT, HTH, THH): $\frac{3}{8}$.`,
    source: SOURCE,
  },
  {
    id: "prob-04",
    topic: "probability",
    difficulty: "medium",
    stem: "Two fair six-sided dice are rolled. What is the probability that the two numbers add up to 7?",
    choices: [
      String.raw`$\frac{1}{12}$`,
      String.raw`$\frac{1}{9}$`,
      String.raw`$\frac{5}{36}$`,
      String.raw`$\frac{1}{6}$`,
      String.raw`$\frac{1}{4}$`,
    ],
    answerIndex: 3,
    explanation: String.raw`Of the 36 equally likely pairs, six sum to 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1). So the probability is $\frac{6}{36} = \frac{1}{6}$.`,
    source: SOURCE,
  },
  {
    id: "prob-05",
    topic: "probability",
    difficulty: "medium",
    stem: "A box holds 2 red and 3 green apples. Two apples are taken out at random, one after the other, without putting the first one back. What is the probability that both are green?",
    choices: [
      String.raw`$\frac{3}{25}$`,
      String.raw`$\frac{6}{25}$`,
      String.raw`$\frac{3}{10}$`,
      String.raw`$\frac{2}{5}$`,
      String.raw`$\frac{9}{20}$`,
    ],
    answerIndex: 2,
    explanation: String.raw`The first apple is green with probability $\frac{3}{5}$; then 2 of the remaining 4 are green: $\frac{3}{5} \times \frac{2}{4} = \frac{3}{10}$.`,
    source: SOURCE,
  },
  {
    id: "prob-06",
    topic: "probability",
    difficulty: "hard",
    stem: "An integer from 1 to 20 is chosen at random. What is the probability that it is divisible by 2 or by 3 (or both)?",
    choices: [
      String.raw`$\frac{1}{2}$`,
      String.raw`$\frac{3}{5}$`,
      String.raw`$\frac{13}{20}$`,
      String.raw`$\frac{7}{10}$`,
      String.raw`$\frac{4}{5}$`,
    ],
    answerIndex: 2,
    explanation: String.raw`There are 10 multiples of 2 and 6 multiples of 3, but the 3 multiples of 6 are counted twice: $10 + 6 - 3 = 13$ favorable outcomes, so $\frac{13}{20}$.`,
    source: SOURCE,
  },

  // ── Data Analysis ──────────────────────────────────────────────────────
  {
    id: "data-01",
    topic: "data-analysis",
    difficulty: "easy",
    stem: "What is the mean (average) of the numbers 4, 7, 8, 9, and 12?",
    choices: ["$6$", "$7$", "$8$", "$9$", "$10$"],
    answerIndex: 2,
    explanation: String.raw`The sum is $4+7+8+9+12 = 40$, and $40 \div 5 = 8$.`,
    source: SOURCE,
  },
  {
    id: "data-02",
    topic: "data-analysis",
    difficulty: "easy",
    stem: "What is the median of the list 3, 9, 5, 7, 11?",
    choices: ["$3$", "$5$", "$7$", "$9$", "$11$"],
    answerIndex: 2,
    explanation:
      "Sorted, the list is 3, 5, 7, 9, 11. The median is the middle value: 7. (Always sort before finding the median.)",
    source: SOURCE,
  },
  {
    id: "data-03",
    topic: "data-analysis",
    difficulty: "medium",
    stem: "After five tests, Aisha's average score is 84. What must she score on her sixth test to raise her average to 86?",
    choices: ["$88$", "$90$", "$92$", "$96$", "$98$"],
    answerIndex: 3,
    explanation: String.raw`Six tests averaging 86 total $6 \times 86 = 516$; her first five total $5 \times 84 = 420$. She needs $516 - 420 = 96$.`,
    source: SOURCE,
  },
  {
    id: "data-04",
    topic: "data-analysis",
    difficulty: "medium",
    stem: "A class of 10 students averaged 80 on a quiz, and another class of 15 students averaged 90. What is the average for all 25 students?",
    choices: ["$84$", "$85$", "$86$", "$87$", "$88$"],
    answerIndex: 2,
    explanation: String.raw`Total points: $10 \times 80 + 15 \times 90 = 800 + 1350 = 2150$. The combined average is $2150 \div 25 = 86$ — closer to 90 because the second class is larger.`,
    source: SOURCE,
  },
  {
    id: "data-05",
    topic: "data-analysis",
    difficulty: "medium",
    stem: "The list $5, 8, 8, 11, x$ has a mean of 9. What is the range of the list?",
    choices: ["$5$", "$6$", "$8$", "$9$", "$13$"],
    answerIndex: 2,
    explanation: String.raw`A mean of 9 over five numbers means the sum is 45, so $x = 45 - 32 = 13$. The range is the largest minus the smallest: $13 - 5 = 8$.`,
    source: SOURCE,
  },
  {
    id: "data-06",
    topic: "data-analysis",
    difficulty: "hard",
    stem: "Five positive integers have a mean of 10 and a median of 12. What is the largest possible value of any of the five integers?",
    choices: ["$22$", "$24$", "$26$", "$28$", "$30$"],
    answerIndex: 1,
    explanation: String.raw`The sum is 50 and the middle value (3rd of 5, sorted) is 12. To make one number as large as possible, make the others as small as allowed: the two below the median can be 1 and 1, and the 4th must be at least 12. That leaves $50 - 1 - 1 - 12 - 12 = 24$.`,
    source: SOURCE,
  },

  // ── Logic & Spatial Reasoning ──────────────────────────────────────────
  {
    id: "logic-01",
    topic: "logic",
    difficulty: "easy",
    stem: "How many edges does a cube have?",
    choices: ["$6$", "$8$", "$10$", "$12$", "$14$"],
    answerIndex: 3,
    explanation:
      "A cube has 4 edges around the top face, 4 around the bottom face, and 4 vertical edges connecting them: 12 in all.",
    source: SOURCE,
  },
  {
    id: "logic-02",
    topic: "logic",
    difficulty: "easy",
    stem: "What is the angle, in degrees, between the hour hand and the minute hand of a clock at exactly 3:00?",
    choices: ["$30$", "$45$", "$60$", "$90$", "$120$"],
    answerIndex: 3,
    explanation: String.raw`At 3:00 the minute hand points at 12 and the hour hand at 3 — a quarter of the way around the clock: $\frac{360}{4} = 90$ degrees.`,
    source: SOURCE,
  },
  {
    id: "logic-03",
    topic: "logic",
    difficulty: "medium",
    stem: "January 1 of a certain year falls on a Tuesday. On what day of the week does January 31 of that year fall?",
    choices: ["Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    answerIndex: 1,
    explanation: String.raw`January 31 is 30 days after January 1. Since $30 = 4 \times 7 + 2$, the day of the week advances by 2: Tuesday $\to$ Thursday.`,
    source: SOURCE,
  },
  {
    id: "logic-04",
    topic: "logic",
    difficulty: "medium",
    stem: String.raw`A $3 \times 3 \times 3$ cube is painted on all six outside faces, then cut into 27 unit cubes. How many of the unit cubes have paint on exactly two faces?`,
    choices: ["$6$", "$8$", "$12$", "$24$", "$26$"],
    answerIndex: 2,
    explanation:
      "Cubes with exactly two painted faces sit on the edges of the big cube but not at its corners. A cube has 12 edges, and each edge of a 3×3×3 cube has exactly one such middle cube: 12.",
    source: SOURCE,
  },
  {
    id: "logic-05",
    topic: "logic",
    difficulty: "medium",
    stem: "Squares are built in a row from toothpicks: one square uses 4 toothpicks, and each additional square shares a side with the previous one, adding 3 more toothpicks. How many toothpicks are needed for a row of 10 squares?",
    choices: ["$28$", "$30$", "$31$", "$34$", "$37$"],
    answerIndex: 2,
    explanation: String.raw`The first square uses 4 toothpicks and each of the other 9 squares adds 3: $4 + 9 \times 3 = 31$.`,
    source: SOURCE,
  },
  {
    id: "logic-06",
    topic: "logic",
    difficulty: "hard",
    stem: "Three positive integers have a product of 36 and a sum of 11. What is the largest of the three integers?",
    choices: ["$4$", "$6$", "$9$", "$12$", "$18$"],
    answerIndex: 1,
    explanation:
      "List the triples of positive integers with product 36 and check their sums: (1, 1, 36), (1, 2, 18), (1, 3, 12), (1, 4, 9), (1, 6, 6), (2, 2, 9), (2, 3, 6), (3, 3, 4) have sums 38, 21, 16, 14, 13, 13, 11, 10. Only (2, 3, 6) sums to 11, so the largest is 6.",
    source: SOURCE,
  },
];
