import type { Question } from "@mathprep/core";

import { SET_02_QUESTIONS } from "./set-02";
import { SET_03_QUESTIONS } from "./set-03";
import { SET_04_QUESTIONS } from "./set-04";
import { SET_05_QUESTIONS } from "./set-05";
import { SET_06_QUESTIONS } from "./set-06";
import { SET_07_QUESTIONS } from "./set-07";

export interface PracticeSet {
  setNumber: number;
  questions: Question[];
}

/**
 * Self-contained 25-question practice sets (mock exams #2+), generated by the
 * author/verify pipeline described in .claude/skills/author-questions/. Each
 * set follows the real AMC 8 shape: positions 1-10 easy, 11-20 medium,
 * 21-25 hard, with an authentic topic distribution.
 */
export const PRACTICE_SETS: PracticeSet[] = [
  { setNumber: 2, questions: SET_02_QUESTIONS },
  { setNumber: 3, questions: SET_03_QUESTIONS },
  { setNumber: 4, questions: SET_04_QUESTIONS },
  { setNumber: 5, questions: SET_05_QUESTIONS },
  { setNumber: 6, questions: SET_06_QUESTIONS },
  { setNumber: 7, questions: SET_07_QUESTIONS },
];
